### ISSUE TITLE
Routing

### ISSUE THREAD

**Issue by ppusapati** [rzvdaniel/svelte-micro-frontends#7]
Have started working on microfrontends using this code. When I have added another module(application) to static-apps in which I use smelte and its components and dynamic data. Am unable to route to other apps without page refresh. 
![Screenshot from 2020-09-15 18-46-06](https://user-images.githubusercontent.com/5749576/93215249-c8364e00-f783-11ea-8457-9c1cbeef67be.png)

**Comment by rzvdaniel** [comment]
Hi, @ppusapati!

Sorry for not coming back to you earlier, I just wasn't on Github for a while.

Have you salved your problem yet? :)

Best!
Razvan

**Comment by ppusapati** [comment]
Hi @rzvdaniel, 

Couldn't solve this and left it as it was. 

-Praveen

**Comment by rzvdaniel** [comment]
Sorry to hear this, the exercise was pretty ... experimental :).
